# Generated by Django 5.1.3 on 2024-11-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
