# Generated by Django 5.1.3 on 2024-11-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
