# Generated by Django 5.1.3 on 2024-11-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_tags'),
        ('tips', '0002_alter_tip_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='category',
        ),
        migrations.AddField(
            model_name='tip',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tips', to='categories.category'),
        ),
    ]
