# Generated by Django 5.1.3 on 2024-12-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_remove_tip_category_tip_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='likes',
        ),
        migrations.AlterField(
            model_name='tip',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
