# Generated by Django 5.1.4 on 2025-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_remove_tip_dislikes_remove_tip_likes_alter_tip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
